language: java

jdk:
  - oraclejdk8

script: "mvn createBooking -DdatabaseEngine=h2"

after_success:
  - mvn -DdatabaseEngine=h2 -Pcobertura clean cobertura:cobertura
  - mvn -DdatabaseEngine=h2 org.eluder.coveralls:coveralls-maven-plugin:report